version: '2'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=dominik
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - "3306:3306"
    networks:
      - php-network

  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - mysql:db
    networks:
      - php-network

networks:
  php-network:
    driver: bridge
